config/routes.rb
Votables::Application.routes.draw do
  resources :votes

  resources :options

  resources :rounds

  resources :votables

  devise_for :users

  resources :home, :only => :index

  root :to => "home#index"
  match '/token' => 'home#index', :as => :token

end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :votable
  has_many :votes

  def complete
    'true'
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  # GET /rounds
  # GET /rounds.xml
  def index
    @rounds = Round.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rounds }
    end
  end

  # GET /rounds/1
  # GET /rounds/1.xml
  def show
    @round = Round.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @round }
    end
  end

  # GET /rounds/new
  # GET /rounds/new.xml
  def new
    @round = Round.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @round }
    end
  end

  # GET /rounds/1/edit
  def edit
    @round = Round.find(params[:id])
  end

  # POST /rounds
  # POST /rounds.xml
  def create
    @round = Round.new(params[:round])

    respond_to do |format|
      if @round.save
        format.html { redirect_to(@round, :notice => 'Round was successfully created.') }
        format.xml  { render :xml => @round, :status => :created, :location => @round }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @round.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rounds/1
  # PUT /rounds/1.xml
  def update
    @round = Round.find(params[:id])

    respond_to do |format|
      if @round.update_attributes(params[:round])
        format.html { redirect_to(@round, :notice => 'Round was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @round.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.xml
  def destroy
    @round = Round.find(params[:id])
    @round.destroy

    respond_to do |format|
      format.html { redirect_to(rounds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :votable_id %><br />
    <%= f.text_field :votable_id %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :allowed_winners %><br />
    <%= f.text_field :allowed_winners %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<h1>Listing rounds</h1>

<table>
  <tr>
    <th>Votable</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>Number</th>
    <th>Allowed winners</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rounds.each do |round| %>
  <tr>
    <td><%= round.votable_id %></td>
    <td><%= round.starts_at %></td>
    <td><%= round.ends_at %></td>
    <td><%= round.number %></td>
    <td><%= round.allowed_winners %></td>
    <td><%= link_to 'Show', round %></td>
    <td><%= link_to 'Edit', edit_round_path(round) %></td>
    <td><%= link_to 'Destroy', round, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Round', new_round_path %>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render 'form' %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Votable:</b>
  <%= @round.votable_id %>
</p>

<p>
  <b>Starts at:</b>
  <%= @round.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @round.ends_at %>
</p>

<p>
  <b>Number:</b>
  <%= @round.number %>
</p>

<p>
  <b>Allowed winners:</b>
  <%= @round.allowed_winners %>
</p>


<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>