config/routes.rb
Votables::Application.routes.draw do
  resources :votes

  resources :options

  resources :rounds

  resources :votables

  devise_for :users

  resources :home, :only => :index

  root :to => "home#index"
  match '/token' => 'home#index', :as => :token

end

app/controllers/votables_controller.rb
class VotablesController < ApplicationController
  # GET /votables
  # GET /votables.xml
  def index
    @votables = Votable.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @votables }
    end
  end

  # GET /votables/1
  # GET /votables/1.xml
  def show
    @votable = Votable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @votable }
      format.json { render :json => @votable.to_json(:include => { :options => {}, :rounds => { :include => :votes, :methods => :complete } }, :methods => :num_voters) }
    end
  end

  # GET /votables/new
  # GET /votables/new.xml
  def new
    @votable = Votable.new
    @votable.rounds.build(:number => 1)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @votable }
    end
  end

  # GET /votables/1/edit
  def edit
    @votable = Votable.find(params[:id])
  end

  # POST /votables
  # POST /votables.xml
  def create
    @votable = Votable.new(params[:votable])

    respond_to do |format|
      if @votable.save
        format.html { redirect_to(@votable, :notice => 'Votable was successfully created.') }
        format.xml  { render :xml => @votable, :status => :created, :location => @votable }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @votable.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /votables/1
  # PUT /votables/1.xml
  def update
    @votable = Votable.find(params[:id])

    respond_to do |format|
      if @votable.update_attributes(params[:votable])
        format.html { redirect_to(@votable, :notice => 'Votable was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @votable.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /votables/1
  # DELETE /votables/1.xml
  def destroy
    @votable = Votable.find(params[:id])
    @votable.destroy

    respond_to do |format|
      format.html { redirect_to(votables_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/votables_helper.rb
module VotablesHelper
end

app/views/votables/_form.html.erb
<%= nested_form_for(@votable) do |f| %>
  <% if @votable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@votable.errors.count, "error") %> prohibited this votable from being saved:</h2>

      <ul>
      <% @votable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="votable-creation-container">
    <div class="field">
      <%= f.label :name, "Name:" %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :votes_per_round, "Votes per round:" %>
      <%= f.text_field :votes_per_round, :size => 1, :value => 1 %>
    </div>
    <br /><br />

    <fieldset class="bordered" id="options">
      <legend>Options</legend>

      <%= f.fields_for :options %>
      <p><%= f.link_to_add "Add an option", :options %></p>
    </fieldset>

    <fieldset class="bordered" id="options">
      <legend>Rounds (Need at least 1!)</legend>
      <%= f.fields_for :rounds %>
      <p><%= f.link_to_add "Add a round", :rounds %></p>
    </fieldset>

    <fieldset class="bordered" id="votable_permissions">
      <legend>Invite friends to Vote!</legend>
      <%= f.fields_for :votable_permissions %>
      <p><%= f.link_to_add "Invite a user", :votable_permissions %></p>
    </fieldset>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votables/_option_fields.html.erb
<p>
  <%= f.label :name %>
  <%= f.text_field :name, :size => 18 %>
  <%= f.label :description %>
  <%= f.text_field :description, :size => 30 %>
  <%= f.link_to_remove "Remove" %>
</p>

app/views/votables/_round_fields.html.erb
<p>
Round <%= %><br />
  <%= f.label :starts_at %>
  <%= f.datetime_select :starts_at %><br />
  <%= f.label :ends_at %>
  <%= f.datetime_select :ends_at %><br />
  <%= f.label :allowed_winners %>
  <%= f.text_field :allowed_winners, :size => 1 %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.link_to_remove "Remove" %>
  <br />
  ----
</p>

app/views/votables/edit.html.erb
<h1>Editing votable</h1>

<%= render 'form' %>

<%= link_to 'Show', @votable %> |
<%= link_to 'Back', votables_path %>

app/views/votables/index.html.erb
<h1>Listing votables</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Votes per round</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votables.each do |votable| %>
  <tr>
    <td><%= votable.name %></td>
    <td><%= votable.votes_per_round %></td>
    <td><%= link_to 'Show', votable %></td>
    <td><%= link_to 'Edit', edit_votable_path(votable) %></td>
    <td><%= link_to 'Destroy', votable, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Votable', new_votable_path %>

app/views/votables/new.html.erb
<h1>Create a New votable!</h1>
It's easy, just pick a start and end date, name it, add some options, then invite your friends
<br \>
<br \>
<%= render 'form' %>

<%= link_to 'Back', votables_path %>

app/views/votables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @votable.name %>
</p>

<p>
  <b>Votes per round:</b>
  <%= @votable.votes_per_round %>
</p>


<%= link_to 'Edit', edit_votable_path(@votable) %> |
<%= link_to 'Back', votables_path %>